import './globals.css'
// import { Inter } from 'next/font/google'
import {NextUiWrapper} from "@/app/components/wrapper/NextUiWrapper";

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
      <NextUiWrapper>
        {children}
      </NextUiWrapper>
      </body>
    </html>
  )
}
